---
title: "Intro slides"
author: 
  - "Levent Neyse"
  - "Lars Vilhuber"
date: June 22 2025
format: 
  revealjs:
    scrollable: true
    margin: 0
    code-overflow: wrap
    reference-location: document
    widescreen: true
    center: true
    transition: slide
    theme: [night, style.css]
    self_contained: false
    logo: logo.png
    footer: ""
    reveal_options:
        slideNumber: true
        previewLinks: false
        chalkboard:
          theme: chalkboard
          toggleNotesButton: true
    reveal_plugins: ["chalkboard"]

---



```{r, child=c(here::here("slides",'00-whoarewe.md'))}
```

## Part 1

[slides](here::here("slides","VfS_Workshop_Neyse.pdf"))

## Part 2


```{r, child=c(here::here("slides",'02-reproducibility.md'))}
```

```{r, child=c(here::here("slides",'02-reproducibility-extra.md'))}
```

## Next 

- [Reproducibility from the start](https://larsvilhuber.github.io/day1-tutorial/#/scenario)
- [Documenting it all](https://larsvilhuber.github.io/readme-presentation/)
